### ISSUE TITLE
would you 

### ISSUE THREAD

**Issue by eva-yx-wang** [guochengqian/ASSANet#5]
Hi, thank you for your contributions ! Could you please provide the Appendix refered in this paper ? Because I don't understand the 'feature patterns' in Fig. 3d, I would appreciate if you help me figure it out!

**Comment by Shadow581** [comment]
Do you have appendix? I also need it.

**Comment by guochengqian** [comment]
Okay. I will upload to arxiv soon

**Comment by guochengqian** [comment]
added in 
https://github.com/guochengqian/ASSANet/blob/main/misc/ASSANet_supplementary.pdf
